name: Alert parent repository on push
on:
  push:
    branches: [ master ]
    paths: '**.yml'

jobs:
  build:
    name: Dispatch to `other-repo`
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          repo: resource-types-website
          owner: GeorgeKhalifa
          event_type: update_resources
